### ISSUE TITLE
PDF displayed on Windows, but not on Mac or Linux

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/PDFViewerFX#16]
Hi @Dansoftowner 

I am trying to open the same PDF on Linux, Mac and Windows. On Windows the PDF will be displayed, on Mac or Linux not:

<img width="1148" alt="Screen Shot 2021-04-18 at 12 45 44" src="https://user-images.githubusercontent.com/9678681/115143175-052e3000-a046-11eb-8186-25db84ca29a3.png">

Attached the PDF file in question.

Any ideas?

Thanks and best regards
Stephan

[wingtsunwelt_40_2016.pdf](https://github.com/Dansoftowner/PDFViewerFX/files/6331092/wingtsunwelt_40_2016.pdf)

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

thanks for reporting this issue!

Is this happening to all PDFs or just for this specific one?

**Comment by stephansann** [comment]
Can't speak for _all_ PDFs, only with this one it caught my eye. Most PDFs surely are okay (otherwise I could use the lib 😉).

The difference with this file compared to the most PDFs I am working with is that it is rather big (100 pages).
Anyhow memory shouldn't be an issue on my Mac (24 GB).

**Comment by Dansoftowner** [comment]
Checkout version `0.8`. 
I've updated the default `pdf.js` version.

Also, you can now switch back to a previous `pdf.js` version:
```java
PDFDisplayer displayer = new PDFDisplayer(PdfJSVersion._2_2_228);
```

If the problem is still present, tell me!:)

**Comment by stephansann** [comment]
Hi @Dansoftowner 
Great job (again) 👏🏻

It now looks good on Mac and on Linux:

<img width="874" alt="Screen Shot 2021-04-18 at 19 16 55" src="https://user-images.githubusercontent.com/9678681/115154401-e9914c80-a07a-11eb-836a-66ecc7342021.png">

Thanks and best regards
Stephan
