### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by carlogaratti** [Dansoftowner/PDFViewerFX#3]
Hi!

i have a file of 1.5M (pdf) 

The application stars correctly but infortunatly thake a lot to open the pdf file.
![Capture](https://user-images.githubusercontent.com/280330/95768458-abbfff80-0cb6-11eb-8526-126723e71038.PNG)

Do you have any suggestion?

Thanks

Simple code
                 OutputStream stream = _202_readAFile_intoAStream_Gdrive.run("1i19zA7oxvrOdKh7SVneeRuHpaOJ1DqvP");
		 ByteArrayInputStream inStream = new ByteArrayInputStream(((ByteArrayOutputStream ) stream).toByteArray() );
		 System.out.println("aaaaa");
		 PDFDisplayer displayer = new PDFDisplayer(inStream);
   		 stage.setScene(new Scene(displayer.toNode())); 
		 stage.show();

**Comment by Dansoftowner** [comment]
Hi!

I made a performance improvement in `v0.7`, hopefully that solves the problem.
